-- SPDX-License-Identifier: GPL-3.0-only
-- FredPD — full database install for HeidiSQL / mariadb CLI. GENERATED by scripts/gen-install-sql.mjs; do not edit.
-- Run it in the SAME database as qbx_core (select it in HeidiSQL first), then start the server.
-- Safe to run again. fredpd_core records every file below as applied and will not re-run it.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS fredpd_migrations (
  id VARCHAR(64) NOT NULL,
  checksum CHAR(64) NOT NULL,
  applied_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- ===================================================================== 001_core.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 001_core: migration bookkeeping, permissions (IMPLEMENTATION.md §4.1), audit (§4.5), units and officers (§4.9),
-- visibility rules (docs/contracts.md §C3) and the per-type-per-year counters behind {{seq}} (§4.8).
--
-- File rules (docs/contracts.md §C7, docs/modules/db.md): statements end with `;` at end of line, every table is
-- CREATE TABLE IF NOT EXISTS, InnoDB, utf8mb4 / utf8mb4_swedish_ci, with created_at. No procedures, triggers or
-- DELIMITER. Never edit this file once it has been applied anywhere (the runners reject a changed checksum); add a
-- new NNN_*.sql instead. Times are UTC DATETIME whatever the server/session time zone: defaults are
-- (UTC_TIMESTAMP()), never CURRENT_TIMESTAMP/NOW(), and there is no ON UPDATE: every writer sets
-- updated_at = UTC_TIMESTAMP() itself. Identifier conventions: citizenid VARCHAR(50) (as qbx_core players.citizenid), Discord
-- snowflakes VARCHAR(20), unit codes VARCHAR(32) (config/units.json), levels 0 standard / 1 begränsad / 2 hemlig.

-- Bookkeeping: one row per applied migration (id = file name) and per applied seed (id = 'seed/<file name>').
-- The runners create this table before reading it; keep this statement identical to MIGRATIONS_TABLE_DDL in
-- scripts/migrate.mjs and resources/[fredpd]/fredpd_core/server/db.lua (packages/types/test/migrations.test.ts
-- compares all three).
CREATE TABLE IF NOT EXISTS fredpd_migrations (
  id VARCHAR(64) NOT NULL,
  checksum CHAR(64) NOT NULL,
  applied_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Discord guild roles, upserted by the bot (IMPLEMENTATION.md §5.9). Deleted roles are kept with deleted = 1 so
-- their grant rows and audit history survive; grant resolution ignores them (docs/contracts.md §C2).
-- Upsert only with INSERT ... ON DUPLICATE KEY UPDATE (drizzle onDuplicateKeyUpdate), never REPLACE INTO:
-- REPLACE deletes the old row first and the ON DELETE CASCADE below then wipes every grant of that role.
CREATE TABLE IF NOT EXISTS fredpd_roles (
  discord_role_id VARCHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  colour INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Discord role colour as 0xRRGGBB',
  position INT NOT NULL DEFAULT 0,
  deleted TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (discord_role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Role -> grant rows ("<type>:<key>", allow or deny). A role holds a key once: the unique key makes the admin
-- matrix an upsert and rules out a row that both allows and denies the same key.
CREATE TABLE IF NOT EXISTS fredpd_role_grants (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  discord_role_id VARCHAR(20) NOT NULL,
  grant_type ENUM('weapon','vehicle','armory','tool','mdt_page','intel_tier','unit','perm') NOT NULL,
  grant_key VARCHAR(64) NOT NULL,
  effect ENUM('allow','deny') NOT NULL DEFAULT 'allow',
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_role_grant (discord_role_id, grant_type, grant_key),
  CONSTRAINT fk_role_grants_role FOREIGN KEY (discord_role_id) REFERENCES fredpd_roles (discord_role_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Discord user <-> game account. license is the FiveM/Rockstar identifier as stored in qbx_core players.license;
-- the portal lists a user's characters from players by it (IMPLEMENTATION.md §5.9). players is utf8mb4_unicode_ci:
-- compare with `p.license = i.license COLLATE utf8mb4_unicode_ci` or use two queries ("Joining qbx tables" in
-- docs/modules/db.md); a plain join fails with ERROR 1267.
CREATE TABLE IF NOT EXISTS fredpd_identities (
  discord_id VARCHAR(20) NOT NULL,
  license VARCHAR(64) NULL,
  last_citizenid VARCHAR(50) NULL,
  last_seen DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (discord_id),
  KEY idx_license (license),
  KEY idx_last_citizenid (last_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Last GrantSet per Discord user (docs/contracts.md §C2 wire shape), used when the service is unreachable.
CREATE TABLE IF NOT EXISTS fredpd_grant_cache (
  discord_id VARCHAR(20) NOT NULL,
  grants JSON NOT NULL,
  computed_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Audit log (IMPLEMENTATION.md §4.5), written only by fredpd_core audit(). Indexes: record history
-- (target_type, target_id); per-officer activity and the obehörig-sökning count (actor_citizenid, created_at);
-- portal-only actors without a character (actor_discord, created_at); the monthly archive move (created_at).
CREATE TABLE IF NOT EXISTS fredpd_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_citizenid VARCHAR(50) NULL,
  actor_discord VARCHAR(20) NULL,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(32) NULL,
  target_id VARCHAR(64) NULL,
  meta JSON NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_target (target_type, target_id),
  KEY idx_actor_created (actor_citizenid, created_at),
  KEY idx_actor_discord_created (actor_discord, created_at),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Rows older than 90 days, moved by the monthly archive command (INSERT ... SELECT then DELETE, same ids).
-- Same shape as fredpd_audit plus archived_at; id is copied, so it is not AUTO_INCREMENT here.
CREATE TABLE IF NOT EXISTS fredpd_audit_archive (
  id BIGINT UNSIGNED NOT NULL,
  actor_citizenid VARCHAR(50) NULL,
  actor_discord VARCHAR(20) NULL,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(32) NULL,
  target_id VARCHAR(64) NULL,
  meta JSON NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  archived_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_target (target_type, target_id),
  KEY idx_actor_created (actor_citizenid, created_at),
  KEY idx_actor_discord_created (actor_discord, created_at),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Unit catalogue, a SQL-side mirror of config/units.json (the config file stays the source of truth; fredpd_core
-- upserts it at start) so the service and reports can join unit labels and order without reading the file.
CREATE TABLE IF NOT EXISTS fredpd_units (
  code VARCHAR(32) NOT NULL,
  callsign_prefix VARCHAR(8) NOT NULL,
  label_key VARCHAR(64) NOT NULL COMMENT 'locale key, e.g. unit.igv',
  home VARCHAR(32) NULL COMMENT 'Hem page variant',
  sort_order SMALLINT NOT NULL DEFAULT 0 COMMENT 'primary-unit order (IMPLEMENTATION.md §4.9)',
  active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Officer identity (IMPLEMENTATION.md §4.9): one row per police character. Records follow the character
-- (citizenid PK); names and ranks follow the Discord user, so one Discord user with two characters has two rows
-- with the same discord_id. uq_discord_citizen is implied by the PK but is kept on purpose: it documents the pair
-- and is the index the bot uses to refresh every row of a Discord user (WHERE discord_id = ?). discord_id alone is
-- deliberately NOT unique. Callsigns are unique within a unit; NULL (no duty yet) may repeat.
CREATE TABLE IF NOT EXISTS fredpd_officers (
  citizenid VARCHAR(50) NOT NULL,
  discord_id VARCHAR(20) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  avatar_url VARCHAR(255) NULL,
  callsign VARCHAR(16) NULL COMMENT 'formats.json callsign, e.g. IGV-07',
  unit VARCHAR(32) NULL COMMENT 'primary unit code',
  rank_role_id VARCHAR(20) NULL COMMENT 'Discord role holding perm:rank:<key>',
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (citizenid),
  UNIQUE KEY uq_discord_citizen (discord_id, citizenid),
  UNIQUE KEY uq_unit_callsign (unit, callsign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Visibility rules (docs/contracts.md §C3), loaded by fredpd_core/server/canview.lua at start and on
-- fredpd:rulesChanged; defaults in db/seed/visibility_rules_default.sql. record_type '*' = every type,
-- level NULL = any level.
CREATE TABLE IF NOT EXISTS fredpd_visibility_rules (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  record_type VARCHAR(32) NOT NULL,
  level TINYINT UNSIGNED NULL CHECK (level <= 2),
  record_status ENUM('open','closed','any') NOT NULL DEFAULT 'any',
  viewer_condition ENUM('any','assigned','handler','unit','tier_gte','perm') NOT NULL,
  condition_value VARCHAR(64) NULL,
  result ENUM('full','masked','notice','none') NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- {{seq}} counters, one per identifier type per year (year in Europe/Stockholm; 0 for a never-resetting counter).
-- Allocate atomically with fredpd_core db.nextSeq(), i.e.
--   INSERT INTO fredpd_sequences (seq_type, year, value) VALUES (?, ?, LAST_INSERT_ID(1))
--   ON DUPLICATE KEY UPDATE value = LAST_INSERT_ID(value + 1)
-- whose insert id is the allocated number.
CREATE TABLE IF NOT EXISTS fredpd_sequences (
  seq_type VARCHAR(32) NOT NULL,
  year SMALLINT UNSIGNED NOT NULL,
  value INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (seq_type, year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('001_core.sql', 'e1155943f70601f8066c7e34a7b4821e314d4a2d40cc72a791c2620f6d8dd5f8') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 002_index.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 002_index: search mirror tables (IMPLEMENTATION.md §4.2). players.charinfo is JSON and cannot be indexed, so
-- searches never touch it; fredpd_core keeps these mirrors current (backfill + qbx_core events, task 1.4).

-- One row per character. Name search: MATCH (firstname, lastname) AGAINST (... IN BOOLEAN MODE) uses ft_name;
-- prefix / sorted lists use idx_name. personnummer backs the personId search type (docs/contracts.md §C4) and is
-- stored normalised as digits with a dash before the last four (YYMMDD-XXXX or YYYYMMDD-XXXX). gender follows
-- qbx charinfo (0 man, 1 kvinna). license = players.license (links characters of one account).
-- InnoDB FULLTEXT skips words shorter than innodb_ft_min_token_size (default 3): see docs/modules/db.md.
CREATE TABLE IF NOT EXISTS fredpd_persons (
  citizenid VARCHAR(50) NOT NULL,
  firstname VARCHAR(64) NOT NULL DEFAULT '',
  lastname VARCHAR(64) NOT NULL DEFAULT '',
  birthdate DATE NULL,
  personnummer VARCHAR(13) NULL,
  gender TINYINT UNSIGNED NULL,
  phone VARCHAR(20) NULL,
  license VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (citizenid),
  KEY idx_name (lastname, firstname),
  KEY idx_personnummer (personnummer),
  FULLTEXT KEY ft_name (firstname, lastname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- One row per owned vehicle. plate is stored normalised the same way detectSearchType() normalises a query
-- (trimmed, upper case, spaces removed), so a lookup is a primary-key hit.
CREATE TABLE IF NOT EXISTS fredpd_vehicles_idx (
  plate VARCHAR(16) NOT NULL,
  citizenid VARCHAR(50) NULL,
  model VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (plate),
  KEY idx_citizenid (citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- qbx_vehicles' player_vehicles is looked up by plate on a mirror miss. Upstream schemas name a plate key `plate`
-- (MariaDB's default name for a single-column key), so IF NOT EXISTS turns this into a no-op there; it only adds
-- the index on installs that lack it. Skipped when player_vehicles does not exist (docs/contracts.md §C7).
-- (runner directive @if-table-exists player_vehicles, rewritten for plain SQL)
ALTER TABLE IF EXISTS player_vehicles ADD INDEX IF NOT EXISTS plate (plate);

INSERT INTO fredpd_migrations (id, checksum) VALUES ('002_index.sql', '7d46115c6def0a594eb4c67dc82f939b9258a81bdcd5a00b7c8639915163beeb') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 003_records.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 003_records: cases, reports, charges, POI sheets, shares and release requests (IMPLEMENTATION.md §5.3).
-- Records are kept, not deleted: child rows reference their case with ON DELETE RESTRICT (the default) unless
-- they are pure attachments (assignees, subjects, drafts), which cascade.
-- Numbering: case_number from formats.json caseNumber ({{seq}} via fredpd_sequences); per-case counters {{n}}
-- (reports.n, evidence.n) are allocated as MAX(n) + 1 inside the transaction that inserts the row, and the
-- (case_id, n) unique key turns a race into a retryable duplicate-key error.

CREATE TABLE IF NOT EXISTS fredpd_cases (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  case_number VARCHAR(32) NOT NULL COMMENT 'e.g. K-123-26',
  title VARCHAR(160) NOT NULL,
  summary TEXT NULL,
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  level TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (level <= 2),
  unit VARCHAR(32) NULL COMMENT 'owning unit code',
  owner_citizenid VARCHAR(50) NULL COMMENT 'handläggare (canView ownerCitizenid)',
  created_by VARCHAR(50) NULL,
  closed_by VARCHAR(50) NULL,
  closed_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_case_number (case_number),
  KEY idx_status_updated (status, updated_at),
  KEY idx_unit_status (unit, status),
  KEY idx_owner (owner_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- canView assignees. idx_citizenid serves "my cases".
CREATE TABLE IF NOT EXISTS fredpd_case_assignees (
  case_id INT UNSIGNED NOT NULL,
  citizenid VARCHAR(50) NOT NULL,
  role ENUM('lead','member') NOT NULL DEFAULT 'member',
  added_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (case_id, citizenid),
  KEY idx_citizenid (citizenid),
  CONSTRAINT fk_case_assignees_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Persons (citizenid) and vehicles (normalised plate) linked to a case. idx_subject answers "cases for this
-- person/vehicle" on the person and vehicle pages (getPersonSummary).
CREATE TABLE IF NOT EXISTS fredpd_case_subjects (
  case_id INT UNSIGNED NOT NULL,
  subject_type ENUM('person','vehicle') NOT NULL,
  subject_id VARCHAR(50) NOT NULL,
  role ENUM('suspect','victim','witness','other') NOT NULL DEFAULT 'other',
  added_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (case_id, subject_type, subject_id),
  KEY idx_subject (subject_type, subject_id),
  CONSTRAINT fk_case_subjects_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Report templates (markdown). unit NULL = offered to every unit.
CREATE TABLE IF NOT EXISTS fredpd_report_templates (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  unit VARCHAR(32) NULL,
  body MEDIUMTEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_unit_name (unit, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Reports always belong to a case: report_number = formats.json reportNumber ({{case}}/{{n}}), n per case.
CREATE TABLE IF NOT EXISTS fredpd_reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  case_id INT UNSIGNED NOT NULL,
  n INT UNSIGNED NOT NULL,
  report_number VARCHAR(48) NOT NULL COMMENT 'e.g. K-123-26/2',
  title VARCHAR(160) NOT NULL,
  body MEDIUMTEXT NOT NULL COMMENT 'markdown-lite',
  template_id INT UNSIGNED NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (level <= 2),
  author_citizenid VARCHAR(50) NOT NULL,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_report_number (report_number),
  UNIQUE KEY uq_case_n (case_id, n),
  KEY idx_author_created (author_citizenid, created_at),
  CONSTRAINT fk_reports_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id),
  CONSTRAINT fk_reports_template FOREIGN KEY (template_id) REFERENCES fredpd_report_templates (id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Editor autosave (debounced, only while focused and dirty). report_id NULL = draft of a new report; one draft
-- per author and existing report.
CREATE TABLE IF NOT EXISTS fredpd_report_drafts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  author_citizenid VARCHAR(50) NOT NULL,
  report_id INT UNSIGNED NULL,
  case_id INT UNSIGNED NULL,
  template_id INT UNSIGNED NULL,
  title VARCHAR(160) NULL,
  body MEDIUMTEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_author_report (author_citizenid, report_id),
  KEY idx_author_updated (author_citizenid, updated_at),
  CONSTRAINT fk_report_drafts_report FOREIGN KEY (report_id) REFERENCES fredpd_reports (id) ON DELETE CASCADE,
  CONSTRAINT fk_report_drafts_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id) ON DELETE CASCADE,
  CONSTRAINT fk_report_drafts_template FOREIGN KEY (template_id) REFERENCES fredpd_report_templates (id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Charge catalogue (Brottskatalog), seeded by db/seed/charges_sv.sql. fine in SEK, jail_min in game minutes.
-- category is an English key (penal, traffic, narcotics, weapons, public_order, other); the UI label comes from
-- the locale. Retire a charge with active = 0 instead of deleting it (records reference it).
CREATE TABLE IF NOT EXISTS fredpd_charges (
  code VARCHAR(16) NOT NULL,
  category VARCHAR(32) NOT NULL,
  title_sv VARCHAR(160) NOT NULL,
  law_ref VARCHAR(96) NOT NULL,
  class ENUM('ordningsbot','bot','fängelse') NOT NULL,
  fine INT UNSIGNED NOT NULL DEFAULT 0,
  jail_min SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Charges applied to a person. title_sv/class/fine/jail_min are snapshots taken when the charge is applied, so
-- later catalogue edits never rewrite history. fine and jail_min are totals for quantity.
CREATE TABLE IF NOT EXISTS fredpd_records (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  citizenid VARCHAR(50) NOT NULL,
  case_id INT UNSIGNED NULL,
  report_id INT UNSIGNED NULL,
  charge_code VARCHAR(16) NOT NULL,
  title_sv VARCHAR(160) NOT NULL,
  class ENUM('ordningsbot','bot','fängelse') NOT NULL,
  quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  fine INT UNSIGNED NOT NULL DEFAULT 0,
  jail_min INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('issued','paid','served','revoked') NOT NULL DEFAULT 'issued',
  issued_by VARCHAR(50) NOT NULL,
  note VARCHAR(255) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_citizen_created (citizenid, created_at),
  KEY idx_case (case_id),
  KEY idx_report (report_id),
  KEY idx_charge (charge_code),
  CONSTRAINT fk_records_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id),
  CONSTRAINT fk_records_report FOREIGN KEY (report_id) REFERENCES fredpd_reports (id),
  CONSTRAINT fk_records_charge FOREIGN KEY (charge_code) REFERENCES fredpd_charges (code) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- POI sheet (person of interest). warnings is a JSON array of warning keys (e.g. ["armed","violent"]).
CREATE TABLE IF NOT EXISTS fredpd_poi (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  citizenid VARCHAR(50) NOT NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (level <= 2),
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  unit VARCHAR(32) NULL,
  owner_citizenid VARCHAR(50) NULL,
  summary TEXT NULL,
  warnings JSON NULL,
  photo_url VARCHAR(255) NULL,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_citizenid (citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Share links (IMPLEMENTATION.md §4.6): the 32-byte base64url token lives only in the URL; the table keeps its
-- sha256 hex so a database leak does not leak working links. Expiry is mandatory; every view is audited.
CREATE TABLE IF NOT EXISTS fredpd_shares (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  token_hash CHAR(64) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  created_by VARCHAR(50) NULL COMMENT 'citizenid',
  created_by_discord VARCHAR(20) NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_viewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_token_hash (token_hash),
  KEY idx_target (target_type, target_id),
  KEY idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- "Begär ut allmän handling". The requester may not know a record id, so target_* is optional and description is
-- the request text. released_body is the masked content exactly as released.
CREATE TABLE IF NOT EXISTS fredpd_release_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  requester_citizenid VARCHAR(50) NULL,
  requester_discord VARCHAR(20) NULL,
  requester_name VARCHAR(100) NULL,
  target_type VARCHAR(32) NULL,
  target_id VARCHAR(64) NULL,
  description TEXT NOT NULL,
  status ENUM('pending','approved','partial','denied') NOT NULL DEFAULT 'pending',
  decided_by VARCHAR(50) NULL,
  decided_at DATETIME NULL,
  decision_note TEXT NULL,
  released_body MEDIUMTEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_status_created (status, created_at),
  KEY idx_target (target_type, target_id),
  KEY idx_requester (requester_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('003_records.sql', '05e5216e0c12a53ce0327097bdf142afe0c88bef748f257350a75741918b8543') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 004_bolo.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 004_bolo: efterlysningar (IMPLEMENTATION.md §5.4). fredpd_bolo keeps in-memory maps activeByPlate /
-- activeByCitizen, rebuilt from idx_active_expires at start; the plate and citizen indexes serve lookups on a miss
-- and the vehicle/person pages. plate is normalised like fredpd_vehicles_idx.plate. A BOLO for an unknown person
-- or an unplated vehicle leaves citizenid/plate NULL and relies on reason.

CREATE TABLE IF NOT EXISTS fredpd_bolos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  kind ENUM('person','vehicle') NOT NULL,
  citizenid VARCHAR(50) NULL,
  plate VARCHAR(16) NULL,
  reason TEXT NOT NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (level <= 2),
  unit VARCHAR(32) NULL,
  issued_by VARCHAR(50) NOT NULL,
  expires_at DATETIME NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  resolved_by VARCHAR(50) NULL,
  resolved_at DATETIME NULL,
  resolve_note VARCHAR(255) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_plate_active (plate, active),
  KEY idx_citizen_active (citizenid, active),
  KEY idx_active_expires (active, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('004_bolo.sql', 'bbc5d9a4e7ebc22906abbda88ece085086b2c6fde41af0320b46aad3fd259869') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 005_dispatch.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 005_dispatch: alerts mirrored from ps-dispatch (IMPLEMENTATION.md §5.5). The Larm page and the portal list
-- open/assigned alerts newest first: idx_status_created.

CREATE TABLE IF NOT EXISTS fredpd_alerts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(16) NOT NULL COMMENT 'dispatch code, e.g. 10-71',
  title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  coords JSON NULL COMMENT '{"x":0,"y":0,"z":0}',
  street VARCHAR(128) NULL,
  priority TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1 highest',
  source VARCHAR(32) NOT NULL DEFAULT 'ps-dispatch',
  meta JSON NULL COMMENT 'generator payload (vehicle, weapon, gender ...)',
  status ENUM('open','assigned','closed') NOT NULL DEFAULT 'open',
  closed_by VARCHAR(50) NULL,
  closed_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Officers assigned to an alert ("Ta larm"). callsign is a snapshot for the history view.
CREATE TABLE IF NOT EXISTS fredpd_alert_units (
  alert_id INT UNSIGNED NOT NULL,
  citizenid VARCHAR(50) NOT NULL,
  callsign VARCHAR(16) NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (alert_id, citizenid),
  KEY idx_citizenid (citizenid),
  CONSTRAINT fk_alert_units_alert FOREIGN KEY (alert_id) REFERENCES fredpd_alerts (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('005_dispatch.sql', 'e8dd10149d13dd41076f5cafce8018af247bc220d7dc5b96543a6cdd262f0c6f') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 006_evidence.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 006_evidence: evidence registered by fredpd_forensics (IMPLEMENTATION.md §5.7). A row can exist before it is
-- linked to a case (collected, handed in); case_id, n and tag are set by "Koppla till ärende".
-- tag = formats.json evidenceTag (B-{{case}}-{{n:3}}), n per case like fredpd_reports.n.
-- chain is a JSON array of custody entries appended on collect / hand-in / analysis / link.

CREATE TABLE IF NOT EXISTS fredpd_evidence (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_uid VARCHAR(64) NOT NULL COMMENT 'evidences item identifier',
  type VARCHAR(32) NOT NULL COMMENT 'fingerprint, dna, blood, casing, toolmark ...',
  case_id INT UNSIGNED NULL,
  n INT UNSIGNED NULL,
  tag VARCHAR(64) NULL COMMENT 'e.g. B-K-123-26-004',
  level TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (level <= 2),
  result JSON NULL,
  collected_by VARCHAR(50) NULL,
  collected_at DATETIME NULL,
  chain JSON NOT NULL DEFAULT '[]',
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_item_uid (item_uid),
  UNIQUE KEY uq_tag (tag),
  UNIQUE KEY uq_case_n (case_id, n),
  CONSTRAINT fk_evidence_case FOREIGN KEY (case_id) REFERENCES fredpd_cases (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('006_evidence.sql', '865bd45b7f1e9fb4dbb5b221b158d136d19c63613cdea86888c827927fd9233c') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 007_intel.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 007_intel: sources, reports, entity graph and missions (IMPLEMENTATION.md §5.8). Everything here is filtered by
-- canView before it leaves the server; real_citizenid is returned only under the intel_source identity cap.
-- status uses the canView record status values (open = active, closed = avslutad).

CREATE TABLE IF NOT EXISTS fredpd_intel_sources (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  codename VARCHAR(64) NOT NULL,
  handler_citizenid VARCHAR(50) NOT NULL,
  reliability ENUM('A','B','C','D') NOT NULL DEFAULT 'C',
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  notes TEXT NULL,
  real_citizenid VARCHAR(50) NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 2 CHECK (level <= 2),
  unit VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_codename (codename),
  KEY idx_handler (handler_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Missions (spaningsuppdrag). lead_citizenid is the plan's `lead` (renamed: LEAD is reserved in MySQL 8).
CREATE TABLE IF NOT EXISTS fredpd_missions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  unit VARCHAR(32) NULL,
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  level TINYINT UNSIGNED NOT NULL DEFAULT 2 CHECK (level <= 2),
  lead_citizenid VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_status_unit (status, unit),
  KEY idx_lead (lead_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

CREATE TABLE IF NOT EXISTS fredpd_mission_members (
  mission_id INT UNSIGNED NOT NULL,
  citizenid VARCHAR(50) NOT NULL,
  role VARCHAR(32) NULL,
  added_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (mission_id, citizenid),
  KEY idx_citizenid (citizenid),
  CONSTRAINT fk_mission_members_mission FOREIGN KEY (mission_id) REFERENCES fredpd_missions (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Intel reports (author = citizenid). reliability grades the information, sources carry their own grade.
CREATE TABLE IF NOT EXISTS fredpd_intel_reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_id INT UNSIGNED NULL,
  mission_id INT UNSIGNED NULL,
  author VARCHAR(50) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  reliability ENUM('A','B','C','D') NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 1 CHECK (level <= 2),
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_source_created (source_id, created_at),
  KEY idx_mission_created (mission_id, created_at),
  KEY idx_author_created (author, created_at),
  CONSTRAINT fk_intel_reports_source FOREIGN KEY (source_id) REFERENCES fredpd_intel_sources (id),
  CONSTRAINT fk_intel_reports_mission FOREIGN KEY (mission_id) REFERENCES fredpd_missions (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Graph nodes. ref points at the real record (citizenid, normalised plate, case number ...); one node per
-- (type, ref). Locations and groups may have ref NULL (then only the label identifies them).
CREATE TABLE IF NOT EXISTS fredpd_intel_entities (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type ENUM('person','vehicle','location','group','case') NOT NULL,
  ref VARCHAR(64) NULL,
  label VARCHAR(128) NOT NULL,
  created_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_type_ref (type, ref),
  KEY idx_label (label)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Graph edges, walked in both directions by getGraph (idx_from_to, idx_to). confidence 0-100.
CREATE TABLE IF NOT EXISTS fredpd_intel_links (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  from_id INT UNSIGNED NOT NULL,
  to_id INT UNSIGNED NOT NULL,
  type VARCHAR(32) NOT NULL COMMENT 'associate, owns, member_of, seen_at ...',
  confidence TINYINT UNSIGNED NOT NULL DEFAULT 50 CHECK (confidence <= 100),
  report_id INT UNSIGNED NULL,
  created_by VARCHAR(50) NOT NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 1 CHECK (level <= 2),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_from_to (from_id, to_id),
  KEY idx_to (to_id),
  KEY idx_report (report_id),
  CONSTRAINT fk_intel_links_from FOREIGN KEY (from_id) REFERENCES fredpd_intel_entities (id) ON DELETE CASCADE,
  CONSTRAINT fk_intel_links_to FOREIGN KEY (to_id) REFERENCES fredpd_intel_entities (id) ON DELETE CASCADE,
  CONSTRAINT fk_intel_links_report FOREIGN KEY (report_id) REFERENCES fredpd_intel_reports (id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('007_intel.sql', '38e82ccc73209f5dcf5cca481920d60df0fad1260ebbb173df4163bda55d30a1') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 008_tablets.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 008_tablets: issued pd_tablet items (IMPLEMENTATION.md §5.2). serial = ox_inventory metadata.serial. Opening a
-- tablet requires the item and revoked = 0; Ledning manages this on the "Surfplattor" page.

CREATE TABLE IF NOT EXISTS fredpd_tablets (
  serial VARCHAR(32) NOT NULL,
  owner_citizenid VARCHAR(50) NULL,
  revoked TINYINT(1) NOT NULL DEFAULT 0,
  revoked_by VARCHAR(50) NULL,
  revoked_at DATETIME NULL,
  revoke_reason VARCHAR(255) NULL,
  issued_by VARCHAR(50) NULL,
  issued_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (serial),
  KEY idx_owner (owner_citizenid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('008_tablets.sql', '0ceebf211bca2440d7ec6b0b73ac51ac2c1e85817aecd342fc00e65c1342eec8') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 009_service.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 009_service: tables owned by apps/service (docs/contracts.md §C7, docs/modules/service.md): portal sessions and
-- uploaded images. Only fredpd_service reads or writes them; FXServer applies this file like every other migration.
-- Same file rules as 001 (docs/modules/db.md): IF NOT EXISTS, InnoDB, utf8mb4_swedish_ci, created_at, no question
-- marks anywhere (oxmysql would bind them).

-- Portal sessions (IMPLEMENTATION.md §4.6). The cookie fredpd_sid carries a random token; only its sha256 hex is
-- stored, so a leaked table does not hand out sessions. csrf_token is echoed by GET /api/session and required as the
-- x-csrf-token header on every write (docs/contracts.md §C10). citizenid is the character picked after login (NULL
-- until then). Expired rows are deleted on login and logout; there is no timer.
CREATE TABLE IF NOT EXISTS fredpd_sessions (
  id CHAR(64) NOT NULL COMMENT 'sha256 hex of the session token',
  discord_id VARCHAR(20) NOT NULL,
  citizenid VARCHAR(50) NULL,
  csrf_token VARCHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_discord (discord_id),
  KEY idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Uploaded images (POST /upload): png, jpeg or webp, at most 5 MB, type sniffed from the bytes. The file lives in
-- UPLOAD_DIR under file_name (random, never the client's name). source = portal (session) or game (HMAC from
-- FXServer). Records that use an image reference it by id.
CREATE TABLE IF NOT EXISTS fredpd_uploads (
  id CHAR(32) NOT NULL COMMENT 'random hex, also the file name stem',
  file_name VARCHAR(64) NOT NULL,
  mime VARCHAR(32) NOT NULL,
  size_bytes INT UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  source ENUM('portal','game') NOT NULL,
  uploader_discord VARCHAR(20) NULL,
  uploader_citizenid VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  UNIQUE KEY uq_file_name (file_name),
  KEY idx_uploader_discord (uploader_discord, created_at),
  KEY idx_uploader_citizenid (uploader_citizenid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('009_service.sql', '83a04c8af006c7ef6d43e8765d58e712af207228bf3b06c20fc864f6c5b15593') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 010_plate_checks.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 010_plate_checks: skyltkontroller (docs/contracts.md §C12, IMPLEMENTATION.md §5.4; owner fredpd_bolo, task 2.6).
-- One row per plate check: the ox_target option "Kontrollera registreringsskylt" (source 'target'), the tablet
-- action checkPlate ('tablet') and ANPR radar hits reported by the qbx_police patch ('radar', no officer). The
-- vehicle page lists the last 20 checks of a plate through idx_plate_created. plate is normalised like
-- fredpd_vehicles_idx.plate (upper case, no whitespace). The table is a log itself, so its rows are not audited
-- (docs/contracts.md §C7); the lookup is audited separately as bolo.check.
-- source is an addition to the §C12 column list (id, plate, officer_citizenid, hit, bolo_id, created_at).

CREATE TABLE IF NOT EXISTS fredpd_plate_checks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plate VARCHAR(16) NOT NULL,
  officer_citizenid VARCHAR(50) NULL,
  hit TINYINT(1) NOT NULL DEFAULT 0,
  bolo_id INT UNSIGNED NULL,
  source VARCHAR(16) NOT NULL DEFAULT 'tablet',
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  PRIMARY KEY (id),
  KEY idx_plate_created (plate, created_at),
  KEY idx_officer_created (officer_citizenid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- BoloResolveInputSchema (packages/types/src/mdt.ts) allows a 500-character note; 004_bolo.sql made the column
-- VARCHAR(255). Widening is idempotent (the same MODIFY on every run is a no-op).
ALTER TABLE fredpd_bolos MODIFY COLUMN resolve_note VARCHAR(500) NULL;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('010_plate_checks.sql', '1bef1a5f785c867e5ebbfd340973cb0445c10e3734694fd670b014833608b85d') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 011_evidence.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 011_evidence: the evidence item behind a fredpd_evidence row, recorded when fredpd_forensics first sees it
-- (docs/modules/forensics.md "Uid registry", docs/deps-verification.md Decision 5.2). evidences lets a client rewrite
-- item metadata (item_uid included) until its security patch is applied, so every later collect / hand-in / analysis
-- event for the uid is compared with these two columns and refused (audited evidence.mismatch) when they differ.
--   item_name  ox_inventory item name (collected_fingerprint, collected_casing ...), set when the row is created
--   ident      evidence identity, set once: 'fingerprint:<string>', 'dna:<string>' or
--              'ballistics:<owner>|<serial>|<weapon type>|<kind>' (NULL until the item carries evidence)
-- Both stay NULL on rows created before this migration and are filled at the next sighting of the item.

ALTER TABLE fredpd_evidence
  ADD COLUMN IF NOT EXISTS item_name VARCHAR(64) NULL COMMENT 'ox_inventory item name first seen for item_uid' AFTER item_uid,
  ADD COLUMN IF NOT EXISTS ident VARCHAR(191) NULL COMMENT 'evidence identity first seen for item_uid' AFTER item_name;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('011_evidence.sql', '73035d6b7bc04c9b6b77468cbf12618db92c9b64eb9708e785fee5ecc87c6ac6') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== 013_records.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- 013_records: additive columns for the Phase 5 writes of fredpd_records (docs/modules/records.md).
--   fredpd_cases.resolution          the closing note of closeCase (the level stays after close, §C14)
--   fredpd_shares.max_level          highest level a share link may show: the creator's tier when it was created, so a
--                                    link never shows more than its creator could read by tier (assignment-only
--                                    access does not travel with a link)
--   fredpd_release_requests.channel  where the request came in: 'station' (ox_target) or 'portal'
-- No ENUMs here (enum values need locale keys, packages/types/test/locales.test.ts). Obehörig sökning needs no table:
-- it counts fredpd_audit rows through idx (actor_citizenid, created_at) on each person lookup.

ALTER TABLE fredpd_cases
  ADD COLUMN IF NOT EXISTS resolution TEXT NULL COMMENT 'closing note (closeCase)' AFTER summary;

ALTER TABLE fredpd_shares
  ADD COLUMN IF NOT EXISTS max_level TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'highest level the link shows' AFTER target_id;

ALTER TABLE fredpd_release_requests
  ADD COLUMN IF NOT EXISTS channel VARCHAR(16) NULL COMMENT 'station | portal' AFTER requester_name;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('013_records.sql', 'e7a55e8fe66ee416ee20a6a88c5897adf7a3564ed192a3432a4360f3698c6ab7') ON DUPLICATE KEY UPDATE id = id;

-- ===================================================================== seed/charges_sv.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- Brottskatalog (fredpd_charges, 003_records.sql): Swedish charges for the game. Sweden has no licence points;
-- traffic consequences beyond the fine (varning / återkallelse) are handled in reports, not here.
--
-- fine is in SEK and game-balanced (not the real amounts); jail_min is game jail time in minutes; class is
-- 'ordningsbot' (on-the-spot fine), 'bot' (böter via strafföreläggande / domstol) or 'fängelse'.
-- law_ref: BrB = brottsbalken, TBL = lag (1951:649) om straff för vissa trafikbrott, TrF = trafikförordningen
-- (1998:1276), VMF = vägmärkesförordningen (2007:90), NSL = narkotikastrafflagen (1968:64), OL = ordningslagen
-- (1993:1617). References are for flavour and must be reviewed by Rami with the values (task 5.4).
-- category keys (labels come from the locale): penal, traffic, narcotics, weapons, public_order, other.
--
-- Codes are permanent: never renumber or reuse one (fredpd_records references them). Retire a charge by setting
-- active = 0 in the admin UI; this seed never touches `active`.
-- Idempotent: applied by the migration runners when new or changed (tracked as seed/charges_sv.sql in
-- fredpd_migrations); existing codes are updated in place, and their updated_at moves only when a value changed.

INSERT INTO fredpd_charges (code, category, title_sv, law_ref, class, fine, jail_min) VALUES
  -- Brottsbalken: liv och hälsa, frihet och frid
  ('BRB-001', 'penal', 'Mord', 'BrB 3 kap. 1 §', 'fängelse', 0, 60),
  ('BRB-002', 'penal', 'Försök till mord', 'BrB 3 kap. 1 och 11 §§', 'fängelse', 0, 40),
  ('BRB-003', 'penal', 'Dråp', 'BrB 3 kap. 2 §', 'fängelse', 0, 45),
  ('BRB-004', 'penal', 'Ringa misshandel', 'BrB 3 kap. 5 § 2 st.', 'bot', 4000, 0),
  ('BRB-005', 'penal', 'Misshandel', 'BrB 3 kap. 5 §', 'fängelse', 5000, 10),
  ('BRB-006', 'penal', 'Grov misshandel', 'BrB 3 kap. 6 §', 'fängelse', 10000, 20),
  ('BRB-007', 'penal', 'Synnerligen grov misshandel', 'BrB 3 kap. 6 § 2 st.', 'fängelse', 15000, 30),
  ('BRB-008', 'penal', 'Vållande till annans död', 'BrB 3 kap. 7 §', 'fängelse', 10000, 15),
  ('BRB-009', 'penal', 'Grovt vållande till annans död', 'BrB 3 kap. 7 § 2 st.', 'fängelse', 20000, 25),
  ('BRB-010', 'penal', 'Framkallande av fara för annan', 'BrB 3 kap. 9 §', 'bot', 8000, 0),
  ('BRB-011', 'penal', 'Människorov', 'BrB 4 kap. 1 §', 'fängelse', 0, 40),
  ('BRB-012', 'penal', 'Olaga frihetsberövande', 'BrB 4 kap. 2 §', 'fängelse', 5000, 20),
  ('BRB-013', 'penal', 'Olaga tvång', 'BrB 4 kap. 4 §', 'fängelse', 5000, 10),
  ('BRB-014', 'penal', 'Olaga hot', 'BrB 4 kap. 5 §', 'fängelse', 3000, 5),
  ('BRB-015', 'penal', 'Grovt olaga hot', 'BrB 4 kap. 5 § 2 st.', 'fängelse', 5000, 15),
  ('BRB-016', 'penal', 'Hemfridsbrott', 'BrB 4 kap. 6 §', 'bot', 5000, 0),
  ('BRB-017', 'penal', 'Olaga intrång', 'BrB 4 kap. 6 § 2 st.', 'bot', 3000, 0),
  ('BRB-018', 'penal', 'Ofredande', 'BrB 4 kap. 7 §', 'bot', 3000, 0),
  -- Brottsbalken: förmögenhetsbrott
  ('BRB-019', 'penal', 'Snatteri', 'BrB 8 kap. 2 §', 'bot', 2000, 0),
  ('BRB-020', 'penal', 'Stöld', 'BrB 8 kap. 1 §', 'fängelse', 3000, 5),
  ('BRB-021', 'penal', 'Grov stöld', 'BrB 8 kap. 4 §', 'fängelse', 8000, 15),
  ('BRB-022', 'penal', 'Rån', 'BrB 8 kap. 5 §', 'fängelse', 10000, 25),
  ('BRB-023', 'penal', 'Grovt rån', 'BrB 8 kap. 6 §', 'fängelse', 20000, 40),
  ('BRB-024', 'penal', 'Försök till rån', 'BrB 8 kap. 5 och 12 §§', 'fängelse', 5000, 15),
  ('BRB-025', 'penal', 'Tillgrepp av fortskaffningsmedel', 'BrB 8 kap. 7 §', 'fängelse', 5000, 10),
  ('BRB-026', 'penal', 'Bedrägeri', 'BrB 9 kap. 1 §', 'fängelse', 5000, 10),
  ('BRB-027', 'penal', 'Grovt bedrägeri', 'BrB 9 kap. 3 §', 'fängelse', 15000, 25),
  ('BRB-028', 'penal', 'Utpressning', 'BrB 9 kap. 4 §', 'fängelse', 10000, 20),
  ('BRB-029', 'penal', 'Häleri', 'BrB 9 kap. 6 §', 'fängelse', 5000, 10),
  ('BRB-030', 'penal', 'Givande av muta', 'BrB 10 kap. 5 b §', 'fängelse', 10000, 10),
  ('BRB-031', 'penal', 'Olovligt brukande', 'BrB 10 kap. 7 §', 'bot', 4000, 0),
  -- Brottsbalken: skadegörelse och allmänfarliga brott
  ('BRB-032', 'penal', 'Ringa skadegörelse', 'BrB 12 kap. 2 §', 'bot', 2000, 0),
  ('BRB-033', 'penal', 'Skadegörelse', 'BrB 12 kap. 1 §', 'bot', 5000, 0),
  ('BRB-034', 'penal', 'Grov skadegörelse', 'BrB 12 kap. 3 §', 'fängelse', 10000, 15),
  ('BRB-035', 'penal', 'Klotter', 'BrB 12 kap. 1 §', 'bot', 3000, 0),
  ('BRB-036', 'penal', 'Mordbrand', 'BrB 13 kap. 1 §', 'fängelse', 10000, 30),
  ('BRB-037', 'penal', 'Grov mordbrand', 'BrB 13 kap. 2 §', 'fängelse', 20000, 45),
  ('BRB-038', 'penal', 'Allmänfarlig ödeläggelse', 'BrB 13 kap. 3 §', 'fängelse', 20000, 40),
  -- Brottsbalken: förfalskning, allmän ordning, rättskipning
  ('BRB-039', 'penal', 'Urkundsförfalskning', 'BrB 14 kap. 1 §', 'fängelse', 5000, 10),
  ('BRB-040', 'penal', 'Penningförfalskning', 'BrB 14 kap. 6 §', 'fängelse', 10000, 20),
  ('BRB-041', 'penal', 'Brukande av falsk handling', 'BrB 14 kap. 10 §', 'bot', 5000, 0),
  ('BRB-042', 'penal', 'Våldsamt upplopp', 'BrB 16 kap. 2 §', 'fängelse', 5000, 15),
  ('BRB-043', 'penal', 'Ohörsamhet mot ordningsmakten', 'BrB 16 kap. 3 §', 'bot', 2500, 0),
  ('BRB-044', 'penal', 'Djurplågeri', 'BrB 16 kap. 13 §', 'bot', 5000, 0),
  ('BRB-045', 'penal', 'Falskt larm', 'BrB 16 kap. 15 §', 'bot', 4000, 0),
  ('BRB-046', 'penal', 'Förargelseväckande beteende', 'BrB 16 kap. 16 §', 'ordningsbot', 1500, 0),
  ('BRB-047', 'penal', 'Våld mot tjänsteman', 'BrB 17 kap. 1 §', 'fängelse', 5000, 15),
  ('BRB-048', 'penal', 'Hot mot tjänsteman', 'BrB 17 kap. 1 §', 'fängelse', 3000, 10),
  ('BRB-049', 'penal', 'Förgripelse mot tjänsteman', 'BrB 17 kap. 2 §', 'bot', 4000, 0),
  ('BRB-050', 'penal', 'Våldsamt motstånd', 'BrB 17 kap. 4 §', 'bot', 5000, 0),
  ('BRB-051', 'penal', 'Övergrepp i rättssak', 'BrB 17 kap. 10 §', 'fängelse', 5000, 15),
  ('BRB-052', 'penal', 'Skyddande av brottsling', 'BrB 17 kap. 11 §', 'bot', 5000, 0),
  ('BRB-053', 'penal', 'Befrielse av fånge', 'BrB 17 kap. 12 §', 'fängelse', 10000, 20),
  ('BRB-054', 'penal', 'Föregivande av allmän ställning', 'BrB 17 kap. 15 §', 'bot', 5000, 0),
  ('BRB-055', 'penal', 'Tjänstefel', 'BrB 20 kap. 1 §', 'bot', 5000, 0),
  -- Trafikbrott (TBL)
  ('TRF-001', 'traffic', 'Vårdslöshet i trafik', 'TBL 1 §', 'bot', 4000, 0),
  ('TRF-002', 'traffic', 'Grov vårdslöshet i trafik', 'TBL 1 § 2 st.', 'fängelse', 8000, 10),
  ('TRF-003', 'traffic', 'Olovlig körning', 'TBL 3 §', 'bot', 4000, 0),
  ('TRF-004', 'traffic', 'Grov olovlig körning', 'TBL 3 § 2 st.', 'fängelse', 5000, 10),
  ('TRF-005', 'traffic', 'Rattfylleri', 'TBL 4 §', 'bot', 6000, 0),
  ('TRF-006', 'traffic', 'Drograttfylleri', 'TBL 4 § 2 st.', 'bot', 6000, 0),
  ('TRF-007', 'traffic', 'Grovt rattfylleri', 'TBL 4 a §', 'fängelse', 10000, 15),
  ('TRF-008', 'traffic', 'Smitning från trafikolycksplats', 'TBL 5 §', 'bot', 5000, 0),
  -- Hastighetsöverträdelse (km/h över tillåten hastighet)
  ('TRF-009', 'traffic', 'Hastighetsöverträdelse 1–10 km/h', 'TrF 3 kap. 17 §', 'ordningsbot', 1500, 0),
  ('TRF-010', 'traffic', 'Hastighetsöverträdelse 11–15 km/h', 'TrF 3 kap. 17 §', 'ordningsbot', 2000, 0),
  ('TRF-011', 'traffic', 'Hastighetsöverträdelse 16–20 km/h', 'TrF 3 kap. 17 §', 'ordningsbot', 2500, 0),
  ('TRF-012', 'traffic', 'Hastighetsöverträdelse 21–25 km/h', 'TrF 3 kap. 17 §', 'ordningsbot', 3000, 0),
  ('TRF-013', 'traffic', 'Hastighetsöverträdelse 26–30 km/h', 'TrF 3 kap. 17 §', 'ordningsbot', 3500, 0),
  ('TRF-014', 'traffic', 'Hastighetsöverträdelse 31–40 km/h', 'TrF 3 kap. 17 §', 'bot', 5000, 0),
  ('TRF-015', 'traffic', 'Hastighetsöverträdelse 41–50 km/h', 'TrF 3 kap. 17 §', 'bot', 7000, 0),
  ('TRF-016', 'traffic', 'Hastighetsöverträdelse 51–60 km/h', 'TrF 3 kap. 17 §', 'bot', 9000, 0),
  ('TRF-017', 'traffic', 'Hastighetsöverträdelse över 60 km/h', 'TrF 3 kap. 17 §', 'bot', 12000, 0),
  -- Trafikregler och fordon
  ('TRF-018', 'traffic', 'Körning mot rött ljus', 'VMF 3 kap.', 'ordningsbot', 3000, 0),
  ('TRF-019', 'traffic', 'Stopplikt ej iakttagen', 'VMF 2 kap.', 'ordningsbot', 2500, 0),
  ('TRF-020', 'traffic', 'Ej lämnat företräde', 'TrF 3 kap.', 'ordningsbot', 2000, 0),
  ('TRF-021', 'traffic', 'Otillåten omkörning', 'TrF 3 kap.', 'ordningsbot', 2500, 0),
  ('TRF-022', 'traffic', 'Ej använt bilbälte', 'TrF 4 kap. 10 §', 'ordningsbot', 1500, 0),
  ('TRF-023', 'traffic', 'Handhållen mobiltelefon under körning', 'TrF 4 kap. 10 e §', 'ordningsbot', 1500, 0),
  ('TRF-024', 'traffic', 'Motorcykel eller moped utan hjälm', 'TrF 4 kap.', 'ordningsbot', 1500, 0),
  ('TRF-025', 'traffic', 'Ej stannat på polismans tecken', 'TrF 2 kap.', 'bot', 4000, 0),
  ('TRF-026', 'traffic', 'Hindrande av utryckningsfordon', 'TrF 2 kap.', 'ordningsbot', 2000, 0),
  ('TRF-027', 'traffic', 'Felparkering', 'TrF 3 kap.', 'ordningsbot', 800, 0),
  ('TRF-028', 'traffic', 'Bristfällig utrustning på fordon', 'Fordonsförordningen (2009:211)', 'ordningsbot', 1500, 0),
  ('TRF-029', 'traffic', 'Brukande av fordon med falska registreringsskyltar', 'Lag (2019:370) om fordons registrering och användning', 'bot', 5000, 0),
  ('TRF-030', 'traffic', 'Ej medfört körkort', 'Körkortsförordningen (1998:980)', 'ordningsbot', 500, 0),
  ('TRF-031', 'traffic', 'Olovlig tävling med fordon', 'TrF 3 kap.', 'bot', 6000, 0),
  ('TRF-032', 'traffic', 'Obehörig användning av blåljus', 'Fordonsförordningen (2009:211)', 'bot', 5000, 0),
  -- Narkotika
  ('NAR-001', 'narcotics', 'Ringa narkotikabrott (eget bruk)', 'NSL 2 §', 'bot', 3000, 0),
  ('NAR-002', 'narcotics', 'Ringa narkotikabrott (innehav)', 'NSL 2 §', 'bot', 4000, 0),
  ('NAR-003', 'narcotics', 'Narkotikabrott', 'NSL 1 §', 'fängelse', 5000, 10),
  ('NAR-004', 'narcotics', 'Narkotikabrott (försäljning)', 'NSL 1 §', 'fängelse', 10000, 15),
  ('NAR-005', 'narcotics', 'Narkotikabrott (odling eller tillverkning)', 'NSL 1 §', 'fängelse', 10000, 20),
  ('NAR-006', 'narcotics', 'Grovt narkotikabrott', 'NSL 3 §', 'fängelse', 20000, 30),
  ('NAR-007', 'narcotics', 'Synnerligen grovt narkotikabrott', 'NSL 3 a §', 'fängelse', 30000, 50),
  ('NAR-008', 'narcotics', 'Narkotikasmuggling', 'Lag (2000:1225) om straff för smuggling 6 §', 'fängelse', 10000, 15),
  ('NAR-009', 'narcotics', 'Grov narkotikasmuggling', 'Lag (2000:1225) om straff för smuggling 6 §', 'fängelse', 20000, 30),
  ('NAR-010', 'narcotics', 'Dopningsbrott', 'Lag (1991:1969) om förbud mot vissa dopningsmedel 3 §', 'bot', 5000, 0),
  ('NAR-011', 'narcotics', 'Grovt dopningsbrott', 'Lag (1991:1969) om förbud mot vissa dopningsmedel 3 a §', 'fängelse', 10000, 15),
  -- Vapen och explosiva varor
  ('VAP-001', 'weapons', 'Ringa vapenbrott', 'Vapenlagen (1996:67) 9 kap. 1 §', 'bot', 5000, 0),
  ('VAP-002', 'weapons', 'Vapenbrott', 'Vapenlagen (1996:67) 9 kap. 1 §', 'fängelse', 5000, 15),
  ('VAP-003', 'weapons', 'Grovt vapenbrott', 'Vapenlagen (1996:67) 9 kap. 1 a §', 'fängelse', 10000, 30),
  ('VAP-004', 'weapons', 'Synnerligen grovt vapenbrott', 'Vapenlagen (1996:67) 9 kap. 1 a § 2 st.', 'fängelse', 20000, 45),
  ('VAP-005', 'weapons', 'Vapenvårdslöshet', 'Vapenlagen (1996:67) 9 kap. 3 §', 'bot', 4000, 0),
  ('VAP-006', 'weapons', 'Olovlig överlåtelse av vapen', 'Vapenlagen (1996:67) 9 kap. 2 §', 'fängelse', 10000, 15),
  ('VAP-007', 'weapons', 'Brott mot knivlagen', 'Lag (1988:254) om förbud beträffande knivar och andra farliga föremål 4 §', 'bot', 3000, 0),
  ('VAP-008', 'weapons', 'Olovligt innehav av explosiv vara', 'Lag (2010:1011) om brandfarliga och explosiva varor 29 §', 'fängelse', 10000, 20),
  ('VAP-009', 'weapons', 'Olovligt innehav av explosiv vara, grovt brott', 'Lag (2010:1011) om brandfarliga och explosiva varor 29 §', 'fängelse', 20000, 35),
  ('VAP-010', 'weapons', 'Vapensmuggling', 'Lag (2000:1225) om straff för smuggling', 'fängelse', 15000, 30),
  ('VAP-011', 'weapons', 'Skjutning inom detaljplanelagt område utan tillstånd', 'OL 3 kap.', 'bot', 5000, 0),
  -- Allmän ordning (ordningslagen och lokala ordningsföreskrifter)
  ('ORD-001', 'public_order', 'Alkoholförtäring på allmän plats', 'Lokala ordningsföreskrifter (OL 3 kap.)', 'ordningsbot', 800, 0),
  ('ORD-002', 'public_order', 'Urinering på allmän plats', 'Lokala ordningsföreskrifter (OL 3 kap.)', 'ordningsbot', 800, 0),
  ('ORD-003', 'public_order', 'Nedskräpning', 'Miljöbalken 29 kap. 7 §', 'ordningsbot', 800, 0),
  ('ORD-004', 'public_order', 'Användning av fyrverkerier utan tillstånd', 'OL 3 kap. 7 §', 'ordningsbot', 1500, 0),
  ('ORD-005', 'public_order', 'Störande av allmän ordning', 'OL 3 kap.', 'bot', 2000, 0),
  ('ORD-006', 'public_order', 'Offentlig tillställning utan tillstånd', 'OL 2 kap. 4 §', 'bot', 5000, 0),
  ('ORD-007', 'public_order', 'Maskering vid allmän sammankomst', 'Lag (2005:900) om förbud mot att bära maskering i vissa fall', 'bot', 3000, 0),
  ('ORD-008', 'public_order', 'Brott mot tillträdesförbud vid idrottsarrangemang', 'Lag (2005:321) om tillträdesförbud vid idrottsarrangemang', 'bot', 3000, 0),
  ('ORD-009', 'public_order', 'Störande buller på allmän plats', 'Lokala ordningsföreskrifter (OL 3 kap.)', 'ordningsbot', 1000, 0),
  ('ORD-010', 'public_order', 'Olovlig försäljning på allmän plats', 'OL 3 kap.', 'ordningsbot', 1500, 0),
  -- Övrigt
  ('OVR-001', 'other', 'Olovlig försäljning av alkohol', 'Alkohollagen (2010:1622) 11 kap.', 'bot', 6000, 0),
  ('OVR-002', 'other', 'Olovlig tillverkning av alkohol (hembränning)', 'Alkohollagen (2010:1622) 11 kap.', 'bot', 5000, 0),
  ('OVR-003', 'other', 'Langning av alkohol', 'Alkohollagen (2010:1622) 11 kap.', 'bot', 4000, 0),
  ('OVR-004', 'other', 'Penningtvättsbrott', 'Lag (2014:307) om straff för penningtvättsbrott 3 §', 'fängelse', 10000, 15),
  ('OVR-005', 'other', 'Grovt penningtvättsbrott', 'Lag (2014:307) om straff för penningtvättsbrott', 'fängelse', 20000, 30),
  ('OVR-006', 'other', 'Smuggling', 'Lag (2000:1225) om straff för smuggling 3 §', 'bot', 5000, 0),
  ('OVR-007', 'other', 'Grov smuggling', 'Lag (2000:1225) om straff för smuggling 5 §', 'fängelse', 15000, 20),
  ('OVR-008', 'other', 'Jaktbrott', 'Jaktlagen (1987:259) 43 §', 'bot', 5000, 0)
ON DUPLICATE KEY UPDATE
  -- updated_at first, while the columns still hold their old values (assignments run left to right): it moves only
  -- when a value really changes, like the ON UPDATE clause that UTC tables cannot have (docs/contracts.md §C7).
  updated_at = IF(BINARY category <=> BINARY VALUES(category) AND BINARY title_sv <=> BINARY VALUES(title_sv)
    AND BINARY law_ref <=> BINARY VALUES(law_ref) AND BINARY class <=> BINARY VALUES(class)
    AND fine <=> VALUES(fine) AND jail_min <=> VALUES(jail_min), updated_at, UTC_TIMESTAMP()),
  category = VALUES(category),
  title_sv = VALUES(title_sv),
  law_ref = VALUES(law_ref),
  class = VALUES(class),
  fine = VALUES(fine),
  jail_min = VALUES(jail_min);

INSERT INTO fredpd_migrations (id, checksum) VALUES ('seed/charges_sv.sql', 'a9d7e90d3151dbb6540846cb2d28fe322e0b9058d0f1763cf433c8bbaa902ede') ON DUPLICATE KEY UPDATE checksum = VALUES(checksum), applied_at = UTC_TIMESTAMP();

-- ===================================================================== seed/report_templates_sv.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- Report templates (fredpd_report_templates, 003_records.sql): Swedish markdown-lite skeletons offered by the report
-- editor (listReportTemplates; unit NULL = every unit). Markdown-lite = # heading, **bold**, - list; rendered as text.
-- Ids 1-99 belong to this seed and are updated in place when it changes (seeds are the source of truth,
-- docs/modules/db.md); templates made in the admin UI get AUTO_INCREMENT ids and are never touched. A template is
-- retired with active = 0, which this seed never writes.

INSERT INTO fredpd_report_templates (id, name, unit, body) VALUES
  (1, 'Anmälan', NULL, '# Anmälan

**Brott:**
**Tid för händelsen:**
**Plats:**

## Målsägande
- Namn:
- Personnummer:
- Telefon:

## Misstänkt
- Namn / signalement:

## Händelseförlopp


## Skador och egendom
-

## Vittnen
-

## Åtgärder
- '),
  (2, 'PM', NULL, '# Promemoria

**Ämne:**
**Datum:**

## Bakgrund


## Iakttagelser


## Bedömning


## Förslag till åtgärd
- '),
  (3, 'Beslagsprotokoll', NULL, '# Beslagsprotokoll

**Beslagsdatum:**
**Plats:**
**Beslag hos (namn, personnummer):**
**Beslagsbeslut fattat av:**

## Beslagtagen egendom
- Nr 1:
- Nr 2:

## Skäl för beslag
- [ ] Bevisbeslag
- [ ] Förverkandebeslag
- [ ] Återställandebeslag

## Förvaring
**Förvaringsplats / bevisförråd:**
**Beslagets innehavare underrättad:** Ja / Nej'),
  (4, 'Förhör', NULL, '# Förhörsprotokoll

**Förhörd (namn, personnummer):**
**Förhörd i egenskap av:** Misstänkt / Målsägande / Vittne
**Tid och plats för förhöret:**
**Förhörsledare:**
**Närvarande:**

## Underrättelser
- Underrättad om misstanke:
- Rätt till försvarare:

## Förhöret


## Genomläst och godkänt
Förhöret har lästs upp / lästs igenom av den hörde och godkänts: Ja / Nej')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  unit = VALUES(unit),
  body = VALUES(body);

INSERT INTO fredpd_migrations (id, checksum) VALUES ('seed/report_templates_sv.sql', '1a0e86fa697d25b2bc3db04a46e1553cd0e91b1be167333ca5967e09d4964714') ON DUPLICATE KEY UPDATE checksum = VALUES(checksum), applied_at = UTC_TIMESTAMP();

-- ===================================================================== seed/visibility_rules_default.sql
-- SPDX-License-Identifier: GPL-3.0-only
-- Default visibility rules for fredpd_visibility_rules (docs/contracts.md §C3; ASSUMED PLAN §5d):
-- permissive for IGV lookups, strict for sources and missions. See docs/modules/grants-canview.md.
--
-- Evaluation: enabled rules matching record_type ('*' = all) / level (NULL = any) / record_status ('any'),
-- by priority DESC then id ASC; the first rule whose viewer_condition holds wins; no match = 'none'.
-- The hard caps in canView (intel_source identity, level above tier) apply afterwards and are not
-- configurable here.
--
-- Priorities: 100 perm override · 95 BOLO level 0 · 90 assigned/handler · 80 unit · 70 tier_gte ·
--             60 intel.read · 50 disabled example · 10 fallback · -1000 id sentinel.
-- Ids are explicit and grouped per record type (case 10–19, report 20–29, evidence 30–39, poi 40–49,
-- bolo 50–59, mission 60–69, intel_report 70–79, intel_source 80–89). Ids 1–998 are reserved for defaults.
-- Rule 999 is a disabled sentinel: after this seed AUTO_INCREMENT is MAX(id) + 1 = 1000, so rules created by
-- admins get ids from 1000 up and never take an id a later default needs (ON DUPLICATE KEY UPDATE id = id
-- would skip such a default without an error). Keep 999 the highest seeded id.
--
-- Idempotent: re-running inserts missing rows and leaves existing ones (including admin edits) untouched.
-- The seed runners re-apply this file whenever its checksum changes (even a comment edit), and every
-- missing default id is then inserted again. So a default rule (ids 1-999) must be switched off with
-- enabled = 0, never deleted: a deleted default rule silently comes back on the next re-apply.
-- packages/types/test/canView.test.ts parses this file and asserts it equals the `rules` array of
-- packages/types/test/fixtures/canView.fixtures.json, so keep one tuple per line in this exact shape.

INSERT INTO fredpd_visibility_rules
  (id, record_type, level, record_status, viewer_condition, condition_value, result, priority, enabled)
VALUES
  -- Cases: open -> assigned/owner or case unit full, anyone else kontaktnotis;
  --        closed -> assigned/owner full, tier >= level masked, else kontaktnotis.
  (10, 'case', NULL, 'any', 'perm', 'records.admin', 'full', 100, 1),
  (11, 'case', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (12, 'case', NULL, 'open', 'unit', NULL, 'full', 80, 1),
  (13, 'case', NULL, 'closed', 'tier_gte', NULL, 'masked', 70, 1),
  (14, 'case', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- Disabled example: enable to let every officer read open cases masked instead of a kontaktnotis.
  (15, 'case', NULL, 'open', 'any', NULL, 'masked', 50, 0),
  -- Reports: as cases.
  (20, 'report', NULL, 'any', 'perm', 'records.admin', 'full', 100, 1),
  (21, 'report', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (22, 'report', NULL, 'open', 'unit', NULL, 'full', 80, 1),
  (23, 'report', NULL, 'closed', 'tier_gte', NULL, 'masked', 70, 1),
  (24, 'report', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- Evidence: as cases.
  (30, 'evidence', NULL, 'any', 'perm', 'records.admin', 'full', 100, 1),
  (31, 'evidence', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (32, 'evidence', NULL, 'open', 'unit', NULL, 'full', 80, 1),
  (33, 'evidence', NULL, 'closed', 'tier_gte', NULL, 'masked', 70, 1),
  (34, 'evidence', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- POI sheets: permissive lookups, anyone with tier >= level reads them in full.
  (40, 'poi', NULL, 'any', 'perm', 'records.admin', 'full', 100, 1),
  (41, 'poi', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (42, 'poi', NULL, 'any', 'unit', NULL, 'full', 80, 1),
  (43, 'poi', NULL, 'any', 'tier_gte', NULL, 'full', 70, 1),
  (44, 'poi', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- BOLO: level 0 full for everyone; higher levels for issuer, unit and tier >= level.
  (50, 'bolo', NULL, 'any', 'perm', 'records.admin', 'full', 100, 1),
  (51, 'bolo', 0, 'any', 'any', NULL, 'full', 95, 1),
  (52, 'bolo', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (53, 'bolo', NULL, 'any', 'unit', NULL, 'full', 80, 1),
  (54, 'bolo', NULL, 'any', 'tier_gte', NULL, 'full', 70, 1),
  (55, 'bolo', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- Missions (strict): members/lead and intel.command full, everyone else kontaktnotis.
  (60, 'mission', NULL, 'any', 'perm', 'intel.command', 'full', 100, 1),
  (61, 'mission', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (62, 'mission', NULL, 'any', 'any', NULL, 'notice', 10, 1),
  -- Intel reports (strict): author/assigned, intel.command, intel.read full (tier cap applies), else none.
  -- OPEN (review accepted option a; §C3 text to be amended): §C3 says intel.read below the report's level
  -- gets none, but one condition per rule cannot express intel.read AND tier_gte, so rule 72 plus the level
  -- cap gives notice (see the module doc).
  (70, 'intel_report', NULL, 'any', 'perm', 'intel.command', 'full', 100, 1),
  (71, 'intel_report', NULL, 'any', 'assigned', NULL, 'full', 90, 1),
  (72, 'intel_report', NULL, 'any', 'perm', 'intel.read', 'full', 60, 1),
  -- Intel sources (strict): handler and intel.command full (identity cap applies), intel.read masked; else none.
  (80, 'intel_source', NULL, 'any', 'perm', 'intel.command', 'full', 100, 1),
  (81, 'intel_source', NULL, 'any', 'handler', NULL, 'full', 90, 1),
  (82, 'intel_source', NULL, 'any', 'perm', 'intel.read', 'masked', 60, 1),
  -- Id sentinel (see the header): disabled, and harmless if enabled ('none' is also the no-match result).
  (999, '*', NULL, 'any', 'any', NULL, 'none', -1000, 0)
ON DUPLICATE KEY UPDATE id = id;

INSERT INTO fredpd_migrations (id, checksum) VALUES ('seed/visibility_rules_default.sql', '6274a792f303a166a5ebcd46092081e25f3b1b97a5f3cc9cfe272f5b090fc13f') ON DUPLICATE KEY UPDATE checksum = VALUES(checksum), applied_at = UTC_TIMESTAMP();

SELECT 'FredPD database installed' AS result, COUNT(*) AS files_recorded FROM fredpd_migrations;
